### ISSUE TITLE
Not able to sign in fastoredis

### ISSUE THREAD

**Issue by pravinfere92** [fastogt/fastoredis#102]
I have signed up in fastoredis website and tried to log in fastoredis using same credentials (This is how we can log in, as per suggestion) but not able to do so. 
It is giving me an error as **sorry, can't connect to server for checking your credentials** 
as attached in the screen shot.

**Note - Internet connection is there for sure.**

![fastoredis issue](https://user-images.githubusercontent.com/53852963/73241592-75922c80-41c8-11ea-9ee8-ff6aea8a0894.PNG)

**Comment by marymizrahi** [comment]
I have not been able to use fastoredis for months.  It's a total waste of money.

**Comment by topilski** [comment]
@marymizrahi can you provide your subscription email? i will check how you paid.

**Comment by marymizrahi** [comment]
mmizrahi@gosecure.net.

**Comment by topilski** [comment]
Yes, you paid for 1 year, and use the application for about 9 months, more than 100 times you have started the application. Where you can't sign in?

**Comment by marymizrahi** [comment]
That is correct.  I gave up using it months ago.  I just tried again today because I received the renewal bill.  It still does not work.

Mary

**Comment by topilski** [comment]
Not reproduced, I can login

**Comment by marymizrahi** [comment]
Yes, it’s working now.  You made some sort of change.
I am not renewing my subscription as I have no idea when it will break again and I have not been able to use it for months.

Mary

**Comment by topilski** [comment]
Ok, np
