### ISSUE TITLE
Not able to view Graphical History Chart on Windows

### ISSUE THREAD

**Issue by Kapil103** [fastogt/fastoredis#57]
Hi All,

I just downloaded latest version for windows from http://fastoredis.com/download_windows.html

I enabled logging from connection dialog window but i am not able to see anything in history.

Can anyone help me ? Waiting for the response.

Regards,
Kapil Akhia

**Comment by Kapil103** [comment]
![redis](https://cloud.githubusercontent.com/assets/6072388/9759516/37d253fe-570b-11e5-9a13-ada410543883.png)

**Comment by topilski** [comment]
Good day, thank you for issue try to reproduce, seems not working now!

**Comment by Kapil103** [comment]
Thanks for reply,
please do let me know once you resolve it.

**Comment by topilski** [comment]
I found where we have bug, will be fixed if you want i can send you new build. And now history chart interval 60 seconds.

**Comment by topilski** [comment]
Fix you can find here: https://github.com/fastogt/fastonosql/commit/82609af91664c887b683da2fb744bc56380ca886

**Comment by Kapil103** [comment]
can i get latest exe file for windows with this resolved ?

**Comment by topilski** [comment]
Yes of course, please specify your email.

**Comment by Kapil103** [comment]
my email id is kapil.akhia@gmail.com

Thanks,
Kapil Akhia
