### ISSUE TITLE
Edit existing connection settings doesn't show existing parameter values

### ISSUE THREAD

**Issue by shouah** [fastogt/fastoredis#58]
On Windows platform, when I edit an existing Redis connection the "Connection Settings" dialog box retains the correct connection name text but the connection parameters always show up as "-h 127.0.0.1 -p 6379 -d \n -r 1" instead of showing up the existing text values

**Comment by topilski** [comment]
Good day @shouah, i try to reproduce your case, but in my environment all worked as properly, can you explain in more detail this issue? Did it happen in cluster connection dialog? Also if it possible attach image with bug, thank you!
![rconnections](https://cloud.githubusercontent.com/assets/4686379/12061204/31a4ce2e-af91-11e5-935a-7f2151e918ab.png)

**Comment by topilski** [comment]
I found this and fix bug solution you can find here: https://github.com/fastogt/fastonosql/commit/0cbfd04b0a30b18105a35314e42aa62918a5f203 , @shouah thank you for using FastoRedis!
