### ISSUE TITLE
Redis cluster discovery button doesn't work with protected Redis configuration

### ISSUE THREAD

**Issue by shouah** [fastogt/fastoredis#59]
Using latest FastoRedis 0.7.9.0, when I add Redis Cluster connection and click on the "Discovery" button this fails with "Connection state: NOAUTH Authentication required" error. This happens even if I specify the "-a XXXXXX" password parameter to the connection (note that the "Test" button succeeds but then it looks like it only does a simple TCP connection check).

**Comment by topilski** [comment]
Yes if you clicked test button you check only availability of redis server, but when you click Discovery application try to execute "CLUSTER NODES" commands and if you doesn't specify you credential this command will be failed. If your pass right credential Discovery must work as needed, it is a bug will be fixed, thank you!

**Comment by topilski** [comment]
Fixed in commit https://github.com/fastogt/fastonosql/commit/0cbfd04b0a30b18105a35314e42aa62918a5f203 , will be released after new year!
