### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by leiguorui** [fastogt/fastoredis#60]
I have installed fastoredis on my ubuntu 15. I want to remove it now. How to do it, please?

**Comment by topilski** [comment]
Good day, apt-get remove fastoredis or dpkg -r fastoredis

**Comment by leiguorui** [comment]
Fine, it works. Thinks!

**Comment by topilski** [comment]
you are welcome!

**Comment by matiasherranz** [comment]
What about for macOS Sierra?

**Comment by topilski** [comment]
Hi @matiasherranz , i think like in previous version move application to trash.

**Comment by matiasherranz** [comment]
@topilski Thanks for the answer. I tried to move it to trash from the Launchpad and didn't work, hence the question. I tried from the Applications folder and worked OK.

Thanks!

**Comment by topilski** [comment]
you are welcome!
