### ISSUE TITLE
Support for Redis Cluster protected by master passcode?

### ISSUE THREAD

**Issue by shouah** [fastogt/fastoredis#61]
I'm using FastoRedis 0.8.0.0 and it doesn't seem function properly when I try to write a key while connected to a multi-master Redis v3.0.6 Cluster protected by passcode.
- Steps to reproduce the issue:
  1) Configure a connection to any of the Redis master instance using the "-a [passcode]" and "-c" option
  2) Open the connection
  3) Create a sample key with a string value
  4) the result windows shows:
  key = name_here
  Value = -> Redirected to slot [xxxx] located at ip_address:port
- Expected behavior:
  FastoRedis will follow the redirect, as per the "-c" connection parameter, and automatically authenticate with the new Master (as per the "-a" parameter) and re-attempt the key creation operation
- Actual behavior:
  Unknown. UI shows the new key on the left navigation but it doesn't actually exists since you can't retrieve the value and using the 'redis-cli" command line to verify the database show the key doesn't exist. Closing the tool and reconnecting shows that key doesn't exist -- indeed.

Note #1:
the above redirect is correctly handled when using the Redis-provided "redis-cli" command line tool and specifying the "-c" parameter. I have to manually re-execute the AUTH and SET commands but that's what's another story.

Note #2:
the redirect problem is also applicable if the connected Master dies or a Slave takes over, and your connection needs to be redirected to a different instance.
##

**Comment by topilski** [comment]
@shouah  thank you for using FastoRedis, it is a very interesting issue, i try to fix it.

**Comment by topilski** [comment]
Hi @shouah , can you install last fastoredis app version and test may be this issue not actual any more?
