### ISSUE TITLE
Load Databases - Amazon Elastic Cache - Redis

### ISSUE THREAD

**Issue by aftabnaveed** [fastogt/fastoredis#65]
When trying to Load Databases from Amazon Elastic Cache I get this error

07:18:33.118: ERR unknown command 'CONFIG'

Amazon Elastic Cache restricts you to execute the config command, is there any workaround to bypass that and just load the database you may want to ?

**Comment by topilski** [comment]
Hi @aftabnaveed , yes it will be implemented, thank you for good suggestion!

**Comment by topilski** [comment]
Implemented in 1.2.0 version, please download it and if work as needed close this issue, thx!

**Comment by aftabnaveed** [comment]
It works now! Thank you.
