### ISSUE TITLE
(History  file not found )  . I have specified log directory . Still not getting graphical view of redis performance.

### ISSUE THREAD

**Issue by skjadhav282** [fastogt/fastoredis#66]

**Comment by topilski** [comment]
Hi, do you check logging options in connection?

**Comment by skjadhav282** [comment]
yes . i did logging option Enabled. Thanks for that

**Comment by skjadhav282** [comment]
but now whenever i m trying to view history and change parameters. it says not responding.
what should i do now?
is fasto redis is not stable on windows 10?

**Comment by topilski** [comment]
Now should work! this is a bug.

**Comment by topilski** [comment]
Which parameters was selected?

**Comment by skjadhav282** [comment]
Actually it is not allowing me to select any option in that window.
i want to view stats graph. Abruptly it shows not responding and shuts down

**Comment by topilski** [comment]
Do you have files in C:\Users\${user}\.config\FastoRedis ? extension .red

**Comment by skjadhav282** [comment]
![bug1](https://cloud.githubusercontent.com/assets/20432056/21253654/487c0b3a-c386-11e6-810e-d54078249d06.png)

**Comment by skjadhav282** [comment]
![bug2](https://cloud.githubusercontent.com/assets/20432056/21253667/5f493f90-c386-11e6-882c-4dc1c838c783.png)

**Comment by skjadhav282** [comment]
I have installed it in D drive.
and i have conf.ini file C:/users/config/fastoredis

**Comment by topilski** [comment]
![image](https://cloud.githubusercontent.com/assets/4686379/21253746/e92cba4e-c371-11e6-8ec8-a4f0e796c3fc.png)
.red file?

**Comment by topilski** [comment]
in preferences history folder

**Comment by skjadhav282** [comment]
![des](https://cloud.githubusercontent.com/assets/20432056/21253825/5edcb1da-c387-11e6-94a8-87cebddeb4ff.png)

**Comment by skjadhav282** [comment]
I do not have that .red file .What is its use in the application ?

**Comment by topilski** [comment]
This file is dump of your redis history, according this file drawing graphics.

**Comment by topilski** [comment]
Can you show me your fastoredis.log

**Comment by topilski** [comment]
Placed in C:\Users\${user}

**Comment by skjadhav282** [comment]
09:16:35.901 FastoRedis [INFO] Logger inited
10:35:01.598 FastoRedis [WARNING] Interrupted exec.
10:35:01.626 FastoRedis [ERROR] History file not found
10:35:10.833 FastoRedis [ERROR] History file not found
10:56:01.499 FastoRedis [ERROR] ERR This instance has cluster support disabled
11:01:01.035 FastoRedis [CRITICAL] ../../src/core/command/command.h:44 Check failed: 0
11:01:20.838 FastoRedis [INFO] Logger inited
11:04:58.336 FastoRedis [INFO] Logger inited
11:17:46.107 FastoRedis [INFO] Logger inited
11:22:20.728 FastoRedis [INFO] Logger inited
11:46:58.913 FastoRedis [WARNING] Interrupted exec.
11:48:39.567 FastoRedis [INFO] Logger inited

**Comment by topilski** [comment]
Thank you for log, what folder specified in preferences for logging? 
![image](https://cloud.githubusercontent.com/assets/4686379/21254021/a4ae7554-c373-11e6-993f-b665e73fd3d7.png)

**Comment by skjadhav282** [comment]
Yes , i have found my .red file in D: drive should i send it to you

**Comment by topilski** [comment]
Sure it will be perfectly!

**Comment by skjadhav282** [comment]
I have mailed it to you.

**Comment by topilski** [comment]
thx

**Comment by skjadhav282** [comment]
Please kindly fix this solution as soon as possible

**Comment by topilski** [comment]
44mb how long worked FastoRedis?

**Comment by topilski** [comment]
Which interval you entered in settings?

**Comment by skjadhav282** [comment]
How much value can we enter in front of 'Logging enabled'

**Comment by skjadhav282** [comment]
I have entered the value as 10

**Comment by topilski** [comment]
Every 10 msec executed INFO command

**Comment by skjadhav282** [comment]
ok so what is the proper value one has to enter

**Comment by topilski** [comment]
1000 msec

**Comment by skjadhav282** [comment]
ok i will try this now and if the application crashes again .I will report it to you.Thanks in advance.

**Comment by topilski** [comment]
Previously remove old red file or rename connection

**Comment by skjadhav282** [comment]
Thank you so much for your help.It's working fine now.

**Comment by skjadhav282** [comment]
Can you also help me in  reading the graph which i have got ?

**Comment by skjadhav282** [comment]
![bug3](https://cloud.githubusercontent.com/assets/20432056/21254625/81fd0138-c38c-11e6-9375-15921351cb88.png)

**Comment by topilski** [comment]
Sure, please execute info command from context menu in serve menu side. We render only integer/doubles values.

**Comment by skjadhav282** [comment]
Thanks

**Comment by topilski** [comment]
You are welcome!
