### ISSUE TITLE
Don't show "Check version" modal on every start

### ISSUE THREAD

**Issue by atrauzzi** [fastogt/fastoredis#68]
![image](https://cloud.githubusercontent.com/assets/115199/22862362/b30f59fe-f0f2-11e6-9782-e228792307ec.png)

From a UX standpoint, it's just not necessary to present the information this way.  You only need to show a modal if there's a new version available.

**Comment by topilski** [comment]
Hi @atrauzzi , you can disable this window by checkout "check autoupdate" in settings.

**Comment by atrauzzi** [comment]
Yeah, but why are you doing it by default?  It's just a nuisance and 99% of people are either going to be annoyed by it or will turn it off.

I actually can't think of a reason why every single time you run an application it should show a modal.  It's just annoying and extremely bad UX.

**Comment by sajjad-naqvi-globant** [comment]
I want to enable auto-update, but still don't want to see the dialog, if my version is already up-to-date. It should show a dialog only if my installed version is out dated.

**Comment by topilski** [comment]
@sajjad-naqvi-globant good suggestion, thx will be done.

**Comment by topilski** [comment]
Dialog should appear only if version is outdated.
