### ISSUE TITLE
Move web links into "Help" menu

### ISSUE THREAD

**Issue by atrauzzi** [fastogt/fastoredis#69]
![image](https://cloud.githubusercontent.com/assets/115199/22862372/ed8a066a-f0f2-11e6-8d38-6345014314ff.png)

More general UX stuff. Toolbars are better off containing functionality pertaining to the task(s) at hand.

**Comment by topilski** [comment]
Hi @atrauzzi , which functionality you suggest instead of this buttons?

**Comment by atrauzzi** [comment]
Either the bar can be removed, or you can put connection-related actions.

**Comment by sallyx** [comment]
👍

**Comment by topilski** [comment]
Hi @sallyx , you also think ti will be better move links into help menu?

**Comment by sallyx** [comment]
Yes.

**Comment by topilski** [comment]
Ok, will be done.

**Comment by topilski** [comment]
Done.
