### ISSUE TITLE
support SSL without tunnel

### ISSUE THREAD

**Issue by jeacott1** [fastogt/fastoredis#70]
Redis Desktop Manager has an option to use SSL protocol without the need for a tunnel, or keys.
This is super convenient. would be nice if fastoredis had the same option.

**Comment by mrichman** [comment]
I can't use Fastoredis because it does not support SSL.

**Comment by topilski** [comment]
I didn't have server with redis SSL for implementation, if you describe how i can create this server, i will implement SSL support.

**Comment by mrichman** [comment]
@topilski you can spin one up in Microsoft Azure. SSL listens on port 6380.

**Comment by topilski** [comment]
@mrichman thanx, will try.

**Comment by topilski** [comment]
Hi @mrichman, @jeacott1, i started implementation, you can try how it works in next release, but with limitation (without private keys and certs). Don't forgot input the password(No AUTH error), when you will be create connection to Azure service.

**Comment by topilski** [comment]
ping
