### ISSUE TITLE
Bug: Crashes on windows if key doesn't exist

### ISSUE THREAD

**Issue by sajjad-naqvi-globant** [fastogt/fastoredis#71]
I am running FastoRedis on Windows 7. If I try to GET any non-existing key, then the program exits without any warning message.

**Comment by topilski** [comment]
Hi @sajjad-naqvi-globant thank you for issue, try to reproduce and fix it.

**Comment by topilski** [comment]
@sajjad-naqvi-globant do you execute GET command via console? or double click in explorer tree?

**Comment by topilski** [comment]
Fixed, thank you!
