### ISSUE TITLE
ERR wrong number of arguments for 'ttl' command

### ISSUE THREAD

**Issue by fenshwey** [fastogt/fastoredis#72]
It connects to redis fine (localhost not unixsocket), it loads up the database fine, loads up the keys fine. But when I click "get", it outputs ERR wrong number of arguments for 'ttl' command.

If i try get another key it outputs wrong number of arguments for type command, then back to ttl, then crashes.

In the command window it shows GET key:name:etc and I can not see a reference to ttl in the command so I dunno whats going on.

I'm on redis 3.0.6, I tried chaning the command version to 3.0.0 but that force crashes fastoredis if i try to get two in a row (both faile with wrong number of arguments for ttl too). I am version 1.7.1.0, but the problem was there on the older version.

Not sure if its a bug, or me doing it wrong, but thought I'd share :-)

**Comment by topilski** [comment]
Thank you for issue, will try to reproduce.

**Comment by topilski** [comment]
Hi @fenshwey , can you find log file and show output here. fastoredis.log you can fine in home directory.

**Comment by fenshwey** [comment]
Hi, I will check FastoNoSQL over the next day or so

**Here is the log file, this line has the "Check Failed"**
../../src/proxy/db/redis/driver.cpp:313 18:03:33.792 FastoRedis [CRITICAL] Check failed: array

**and this is the whole log**

17:45:15.731 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:825 17:45:23.315 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
17:47:07.393 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:825 17:47:15.523 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
17:48:39.596 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
17:49:55.249 FastoRedis [ERROR] I/O error
17:52:06.538 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:825 17:52:28.774 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
17:54:50.989 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:825 17:55:08.614 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
03:19:40.432 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:825 03:21:09.718 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
02:29:25.612 FastoRedis [ERROR] I/O error
16:49:23.456 FastoRedis [ERROR] I/O error
16:59:42.158 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
17:17:20.078 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
17:27:16.438 FastoRedis [ERROR] ERR wrong number of arguments for 'get' command
17:27:55.153 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
17:28:49.427 FastoRedis [ERROR] ERR wrong number of arguments for 'type' command
17:29:04.898 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
17:50:50.038 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
17:52:09.402 FastoRedis [ERROR] Invalid input argument for command: 'GET', passed 2 arguments, must be in range 1 - 1.
17:52:25.556 FastoRedis [ERROR] ERR wrong number of arguments for 'type' command
17:52:39.704 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:873 17:56:23.021 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
17:57:33.926 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
17:58:02.259 FastoRedis [ERROR] ERR wrong number of arguments for 'type' command
17:58:08.236 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
17:58:19.247 FastoRedis [ERROR] Empty command line.
../../src/core/db/redis/db_connection.cpp:873 17:59:29.653 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
18:02:02.416 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
18:02:22.340 FastoRedis [ERROR] ERR wrong number of arguments for 'type' command
18:02:28.221 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:873 18:02:48.590 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
20:18:51.684 FastoRedis [ERROR] Empty command line.
20:19:37.839 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
20:19:56.678 FastoRedis [ERROR] ERR wrong number of arguments for 'type' command
20:20:13.916 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:873 20:20:20.418 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
20:21:03.622 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
20:21:19.440 FastoRedis [ERROR] Empty command line.
20:21:51.096 FastoRedis [ERROR] ERR wrong number of arguments for 'type' command
20:21:52.658 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:873 20:21:54.174 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
17:43:42.356 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:873 17:57:43.318 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.
18:01:10.719 FastoRedis [ERROR] I/O error
18:01:51.042 FastoRedis [ERROR] ERR wrong number of arguments for 'get' command
18:02:41.581 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
18:03:20.385 FastoRedis [ERROR] I/O error
../../src/proxy/db/redis/driver.cpp:313 18:03:33.792 FastoRedis [CRITICAL] Check failed: array.
18:04:22.186 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
18:21:46.054 FastoRedis [ERROR] ERR wrong number of arguments for 'ttl' command
../../src/core/db/redis/db_connection.cpp:873 23:13:37.427 FastoRedis [CRITICAL] NOTREACHED() hit in GetImpl.

**Comment by topilski** [comment]
Not reproduced, did you have binary keys in you redis instance?

**Comment by fenshwey** [comment]
Yes. It is actually a partial binary that I pass to redis. It is (login:)++(sha256(email)). The sha256 function returning a binary. 

I can see fastorredis, and my app display it differently below is either 1@1.com, or 2@2.com nothing personal.

1: how fastorredis shows it.
\x6C\x6F\x67\x69\x6E\x3A\x14\xAE\x3D\xD7\x33\x49\x1C\x76\xBD\x64\xB9\x42\xA9\x9A\xCD\x49\xB9\xF2\xD7\xAC\x7F\x1E\x74\xB5\x16\xF7\x23\x34\x43\xF0\x5A\xF6

2: How another app shows it.
login:�=�3Iv�d�B���I��׬t��#4C�Z�

3: How my code shows it
[108,111,103,105,110,58|<<20,174,61,215,51,73,28,118,189,100,185,66,169,154,205,73,185,242,215,172,127,30,...>>]

I also have some characters that cause the main app no problem, but might cause others a problem. Them keys will be removed eventually, they are { } " ' , 

I'd forgotten about them keys.

**Comment by topilski** [comment]
Very interesting case, thank you, will try to add key like you have.

**Comment by fenshwey** [comment]
I did some testing myself and can confirm it is as you guessed the binary keyname causing the problem.

In redis-cli i added keys to 1. I loaded up fastorredis, selected 1, didn't even attempt to load 0, and it all seemed to work just fine. Keys loaded up, I could edit them etc.

It's my own fault, i knew when I did that keyname it was funky lol.
