### ISSUE TITLE
Cant save config and restore

### ISSUE THREAD

**Issue by arquio** [fastogt/fastoredis#73]
Fedora 26 x86_64

FastoRedis 1.7.0.0
Revision:98c42fa

and 

FastoRedis 1.8.1.0
Revision:c776bee

**Comment by topilski** [comment]
Hi, @arquio thank you for issue, will try to reproduce.

**Comment by arquio** [comment]
Same issue with fastoNosql.

**Comment by topilski** [comment]
Hi @arquio , thank you for issue, i will try to fix, i promise you. I need to install Fedora, give me please 1 week.

**Comment by topilski** [comment]
Hi @arquio , fixed in FastoRedis 1.8.7 version, you can test.

**Comment by topilski** [comment]
ping

**Comment by arquio** [comment]
Sorry, I was away. 
I'm testing 1.8.8-1 and its all right.

Thanks a lot!!

**Comment by topilski** [comment]
@arquio you are welcome!
