### ISSUE TITLE
decrement becomes self increment

### ISSUE THREAD

**Issue by Kerwin1202** [fastogt/fastoredis#74]
when i use command to decrement, but it become increment, you can see [http://img.zhanghuanglong.com//image/2017/10/14/20171014192214412069.gif](http://img.zhanghuanglong.com//image/2017/10/14/20171014192214412069.gif)

1. DECR
2. DECRBY

FastoRedis 1.8.6.0 windows

**Comment by topilski** [comment]
Thank you will be fixed

**Comment by topilski** [comment]
Fixed https://github.com/fastogt/fastonosql/commit/71bb1021e339565315c72d564066d92226c1572e
