### ISSUE TITLE
Available old download package for linux

### ISSUE THREAD

**Issue by shakenfr** [fastogt/fastoredis#78]
hello,
last version does'nt not work on RHEL7

[osadmin@localhost bin]$ ./FastoRedis --help
./FastoRedis: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./FastoRedis)
./FastoRedis: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./FastoRedis)
./FastoRedis: /lib64/libQt5Core.so.5: version `Qt_5.9' not found (required by ./FastoRedis)

Requires gcc4.9, new version of libstdc++.so.6 that is not inside RHEL repos.

Is it possible to have and old version of the package to test ?

**Comment by topilski** [comment]
Hi @shakenfr why you trying to start ./FastoRedis, please start fastonosql.sh script which placed near.

**Comment by topilski** [comment]
It will be good to me see output of `ldd FastoRedis` command .

**Comment by shakenfr** [comment]
hello,

here is the result of the ldd command. In fact version of libstdc++.so.6 includes CXXABI_1.3.7 and not CXXABI_1.3.8. Its due to the "old" lib included in RHEL7. Same it's gcc 4.8 and not 4.9. 4.9 is not available in the repos of RHEL7, not into the extras repo too :-(

I add the result of strings libstdc++.so.6 command at the end.
For me I suppose that Fastoredis last version has been compiled with gcc 4.9 thats includes theses libs versions.

[osadmin@localhost bin]$ ./fastoredis
/opt/fastoredis/bin/FastoRedis: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/fastoredis/bin/FastoRedis)
/opt/fastoredis/bin/FastoRedis: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/fastoredis/bin/FastoRedis)
/opt/fastoredis/bin/FastoRedis: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/fastoredis/bin/../lib/libQt5Core.so.5)
[osadmin@localhost bin]$ ./FastoRedis
./FastoRedis: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./FastoRedis)
./FastoRedis: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./FastoRedis)
./FastoRedis: /lib64/libQt5Core.so.5: version `Qt_5.9' not found (required by ./FastoRedis)
[osadmin@localhost bin]$ ldd FastoRedis
./FastoRedis: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./FastoRedis)
./FastoRedis: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./FastoRedis)
./FastoRedis: /lib64/libQt5Core.so.5: version `Qt_5.9' not found (required by ./FastoRedis)
        linux-vdso.so.1 =>  (0x00007ffee7166000)
        libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007f7f431bb000)
        libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007f7f42c7c000)
        libQt5DBus.so.5 => /lib64/libQt5DBus.so.5 (0x00007f7f42bf8000)
        libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007f7f4276f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7f42553000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f7f4234e000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f7f42046000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f7f41d44000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7f41b2d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f7f4176a000)
        /lib64/ld-linux-x86-64.so.2 (0x000055e0f1aa7000)
        libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f7f4151a000)
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f7f41207000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f7f40ff5000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f7f40cb7000)
        libGL.so.1 => /lib64/libGL.so.1 (0x00007f7f40a44000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f7f4082e000)
        libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f7f40603000)
        libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f7f403ba000)
        libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007f7f3ffbc000)
        libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007f7f3fc43000)
        libicudata.so.50 => /lib64/libicudata.so.50 (0x00007f7f3e66e000)
        libpcre16.so.0 => /lib64/libpcre16.so.0 (0x00007f7f3e415000)
        libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f7f3e213000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f7f3e00a000)
        libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f7f3dfe2000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f7f3dd7f000)
        libffi.so.6 => /lib64/libffi.so.6 (0x00007f7f3db77000)
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f7f3d94f000)
        libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f7f3d724000)
        libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00007f7f3d521000)
        libxcb-present.so.0 => /lib64/libxcb-present.so.0 (0x00007f7f3d31e000)
        libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00007f7f3d116000)
        libxshmfence.so.1 => /lib64/libxshmfence.so.1 (0x00007f7f3cf14000)
        libglapi.so.0 => /lib64/libglapi.so.0 (0x00007f7f3cce5000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f7f3cabd000)
        libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f7f3c8ba000)
        libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f7f3c6b4000)
        libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007f7f3c4b1000)
        libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00007f7f3c296000)
        libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00007f7f3c091000)
        libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007f7f3be8a000)
        libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f7f3bc7b000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f7f3ba75000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f7f3b84f000)
        libgcrypt.so.11 => /lib64/libgcrypt.so.11 (0x00007f7f3b5ce000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f7f3b3c8000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f7f3b1ae000)
        libdw.so.1 => /lib64/libdw.so.1 (0x00007f7f3af67000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f7f3ad62000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007f7f3ab5d000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00007f7f3a944000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f7f3a734000)

[osadmin@localhost bin]$ strings /lib64/libstdc++.so.6|grep CXXABI_1.3.8
[osadmin@localhost bin]$ strings /lib64/libstdc++.so.6|grep CXXABI_1.3
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
[osadmin@localhost bin]$ strings /lib64/libstdc++.so.6|grep GLIBCXX_3.4
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
[osadmin@localhost bin]$ strings /lib64/libstdc++.so.6|grep GLIBCXX_3.42.20
[osadmin@localhost bin]$ ./FastoRedis
./FastoRedis: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./FastoRedis)
./FastoRedis: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./FastoRedis)
./FastoRedis: /lib64/libQt5Core.so.5: version `Qt_5.9' not found (required by ./FastoRedis)
[osadmin@localhost bin]$ strings /lib64/libQt5Core.so.5|grep QT_5.9
[osadmin@localhost bin]$ strings /lib64/libQt5Core.so.5|grep QT_5.8
[osadmin@localhost bin]$ strings /lib64/libQt5Core.so.5|grep QT_5
[osadmin@localhost bin]$ strings /lib64/libQt5Core.so.5|grep Qt_5
Qt_5_PRIVATE_API
Qt_5
Qt_5.0
Qt_5.1
Qt_5.2
Qt_5.3
Qt_5.4
Qt_5.5
Qt_5.6
[osadmin@localhost bin]$

**Comment by topilski** [comment]
Hi @shakenfr thank you fore reply, so solution can be 2.
1) You try to build FastoRedis from sources
2) You subscribe and will receive last stable FastoRedis build. (it takes 1 day, we need to create build machine for RHEL7 os)

**Comment by shakenfr** [comment]
I will try 1.
For 2, it's not urgent, you can take your 1 day without problems

best
bruno

**Comment by topilski** [comment]
Ok, thank you.

**Comment by shakenfr** [comment]
for 1-)   i'm looking for sources without success, have you a link ?

**Comment by topilski** [comment]
Save your time, subscribe please, sources you can find here: https://github.com/fastogt/fastonosql
