### ISSUE TITLE
OpenSource? How? Where?

### ISSUE THREAD

**Issue by rbeer** [fastogt/fastoredis#79]
fastoredis.com says:
> FastoRedis (fork of FastoNoSQL) - is a cross-platform open source Redis management tool (i.e. Admin GUI).

No it's not. Where is the code?

**Comment by topilski** [comment]
Hi @rbeer , code you can find here https://github.com/fastogt/fastonosql .

**Comment by TemaSM** [comment]
@topilski How about to upload source soon? Hope you will.
Thanks for software 😉
