### ISSUE TITLE
can't connect using ssh

### ISSUE THREAD

**Issue by wongoo** [fastogt/fastoredis#80]
why ssh connection need public key? Only provide private key can't connect, while the RDM can connect using the same key.

**Comment by topilski** [comment]
Yes your are right, need to add this ability thank you!

**Comment by topilski** [comment]
Hi @wongoo , according libssh2 implementation https://github.com/libssh2/libssh2/blob/a68356418d503c0546bd475fb4e363954add1c84/src/userauth.c#L1457 if you specify public key it will be read from file if not will be generate from private part of key. If you interesting how it works.

**Comment by topilski** [comment]
Hi @wongoo , also i'am interested in which os you using?

**Comment by topilski** [comment]
Fixed: https://github.com/fastogt/fastonosql/commit/9b2334a841b4dd6299e59c7409ac09ba3a75d318

**Comment by wongoo** [comment]
@topilski  macos, 10.13.2

**Comment by topilski** [comment]
Thank you, i will test on Mac.

**Comment by topilski** [comment]
Tested, you can try.
