### ISSUE TITLE
How connect to Heroku Redis

### ISSUE THREAD

**Issue by mishelen** [fastogt/fastoredis#83]
Im just have such url: 
redis://h:j324jlfddsfls.......dfldlsf@ec320-323-323.compute-1.amazonaws.com:port

**Comment by topilski** [comment]
Hi, i need to test Heroku

**Comment by mishelen** [comment]
Solved))

**Comment by topilski** [comment]
Please describe.

**Comment by mishelen** [comment]
1. discard first part or url: `redis://h:`
2. next part is password. also you need to launch checkbox **Use AUTH** in connection window, and place password in next to it input
3. and accordingly set the host (`ec320-323-323.compute-1.amazonaws.com`) and port in inputs

**Comment by topilski** [comment]
Cool, thank you for the solution!
