### ISSUE TITLE
SSH Tunnel and SSL are exclusive

### ISSUE THREAD

**Issue by cfroese** [fastogt/fastoredis#84]
For the most part, this exclusion makes sense.  However, when use AWS ElastiCache Redis with in-transit encryption means connecting requires a SSH tunnel and then an SSL connection through that.

It would be nice if FastoRedis supported this.

**Comment by topilski** [comment]
I need some server to test this connection. Where i can find it, may be you know?

**Comment by topilski** [comment]
Hi @cfroese , why you think that EC2 need ssl connection? Here my settings:
![default](https://user-images.githubusercontent.com/4686379/38765768-351fa142-3fd0-11e8-92ec-c72ab1290e3a.png)
Where in database path: your cluster url
in ssh: your EC2 instance

for generate public key from pem i used: `ssh-keygen -f test.pem -y > test.pub`

**Comment by topilski** [comment]
I unerstand you, thanks, will think how to implement it.

**Comment by topilski** [comment]
Hi @cfroese , implemented in version 1.24, please check, thank you for the issue.
