### ISSUE TITLE
Its not possible to delet all my data in profile. I will do it!

### ISSUE THREAD

**Issue by terbach** [fastogt/fastoredis#87]

**Comment by topilski** [comment]
Hi what you mean?

**Comment by terbach** [comment]
I cannot delete my account at fastoredis webpage.

**Comment by topilski** [comment]
We have delete button, in profile page.

**Comment by topilski** [comment]
![default](https://user-images.githubusercontent.com/4686379/43308605-c5b4b862-918a-11e8-88f7-ecaf31afea6c.png)

**Comment by terbach** [comment]
I have a free subscription and can't see a button. I only can change my name and password.

**Comment by topilski** [comment]
please write me your email on website, i will check

**Comment by topilski** [comment]
removed account
