### ISSUE TITLE
Deleting multiple keys UI

### ISSUE THREAD

**Issue by WillJonesMagic** [fastogt/fastoredis#92]
When selecting and deleting multiple keys, the Mac version asks for confirmation before deleting every single key. 
It would be far more user friendly (as well as less frustrating and more in keeping with various design guidelines and convention) to prompt for confirmation once when multiple keys are selected instead of multiple times.

**Comment by topilski** [comment]
Hi @WillJonesMagic , it is a good idea, will be implemented in next release

**Comment by topilski** [comment]
Also please try del keypress.

**Comment by topilski** [comment]
Hi @WillJonesMagic , fixed please check in new version
