### ISSUE TITLE
json string can't show with json, "cannot  convert to 'Json' format!"

### ISSUE THREAD

**Issue by dahai2070** [fastogt/fastoredis#94]
`{"@type":"com.mytx.pojo.Advertisement","amount":0.15D,"auctionEndDate":1548644400000,"auctionStartDate":1548561600000,"endDate":1548734400000,"id":"201901279380549626","myFile":{"id":"1547184459479325","status":2,"type":1,"uId":"147089748a194bd396976fd343b5e16c","updated":1548585820346,"url":"http://mytx.file.alimmdn.com/video/1547184459479325"},"oId":"201901277605065989","rId":"19b8e3c8e4234b5fb971fb798c2e2aa1","startDate":1548648000000,"title":"fffffffffffffffffffffffff","updateCount":1,"updated":1548585820346,"video":"http://mytx.file.alimmdn.com/video/1547184459479325"}
`

**Comment by topilski** [comment]
Hi, please use text format converters

**Comment by topilski** [comment]
Invalid json, according this site: https://jsoneditoronline.org/

**Comment by topilski** [comment]
0.15D it is invalid

**Comment by dahai2070** [comment]
谢谢你。
